version: '3.8'

services:
  agentic-dev-tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # React frontend
      - "5000:5000"  # Flask backend
    volumes:
      - ${HOME}:/host_home  # Mount user's home directory
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-YOUR_HUGGINGFACE_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - AZURE_API_KEY=${AZURE_API_KEY:-}
    restart: unless-stopped
    tty: true
    stdin_open: true